### ISSUE TITLE
Provide instructions, please

### ISSUE THREAD

**Issue by beraldoleal** [Laurent26/techdraw#2]
Hi @Laurent26 , first thank you for this great plugin.

I tried to reproduce your steps in your youtube videos, but without success. Lines are not as same as your described even when configured as you. Also font is not clear. Can you please provide instructions and/or a default startup settings?

Here is an output example:

![output](https://user-images.githubusercontent.com/49336/117549983-ef43d780-b013-11eb-9d83-a72c27b8045a.png)

**Comment by Laurent26** [comment]
[](url)

**Comment by Laurent26** [comment]
Hi, I just did a test with blender 2.92 and it works fine. I modified the templates so you can re-download the addon. So in the Freestyle Settings tab, you have to select the different collections and add the lines (with 'Edge Mark selected for the Landscape and Type collections). If you still have problems I would do a simple video to explain again otherwise if you can share your file for me to watch.
Cordially.

**Comment by beraldoleal** [comment]
Thank you for your quick reply. I managed to make this work. I'm still trying to get better, but this is a really nice plugin. I'm looking forward for the upgrades.

Nice job!
